[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	set noshowmode
	let g:lightline = {
		\ 'colorscheme': 'wombat',
		\ }
'''

# for replace
[[plugins]]
repo = 'markonm/traces.vim'

# comment
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
	let g:cheatsheet#cheat_file = '~/.vim/cheatsheet.md'
	nnoremap <silent> <C-h> :Cheat<CR>
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
	nnoremap <silent> <leader>f :Denite file/rec<CR>
	nnoremap <silent> <leader>b :Denite buffer<CR>
	nnoremap <silent> <leader>g :Denite grep<CR>
	nnoremap <silent> <leader>l :Denite line<CR>
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
	set helplang=ja
'''


###[[plugins]]
###repo = 'scrooloose/nerdtree'
###hook_add = '''
###	" NERDTree key
###	nnoremap <silent><C-e> :NERDTreeToggle<CR>
###	" default NERDTree activate(damesou?)
###	"let g:nerdtree_tabs_open_on_console_startup=1
###	" show secret file
###	let NERDTreeShowHidden = 1
###	" ikkinitojiruyatu
###	autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
###'''
###
#### for nerdtree
###[[plugins]]
###repo = 'jistr/vim-nerdtree-tabs'

