set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'fatih/vim-go'
Plugin 'markonm/traces.vim'
Plugin 'reireias/vim-cheatsheet'

call vundle#end()
filetype plugin indent on

""" std config
syntax on
set nu
set title
set virtualedit=onemore
set hlsearch
hi Comment ctermfg=Blue

"tab
set tabstop=2
set shiftwidth=2
set softtabstop=2
"set expandtab
set autoindent
set smartindent

"Case-insensitive when searching
set ignorecase
"Use capital letters to distinguish
set smartcase

"Disable arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

" shift-o de sitani gyouwo ireruyo
nnoremap O :<C-u>call append(expand('.'), '')<Cr>j

" NERDTree key
nnoremap <silent><C-e> :NERDTreeToggle<CR>
" default NERDTree activate(damesou?)
let g:nerdtree_tabs_open_on_console_startup=1
" show secret file
let NERDTreeShowHidden = 1
" tab move
nnoremap <Tab>l gt
nnoremap <Tab>h gT
" ikkinitojiruyatu
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Cheetsheet
let g:cheatsheet#cheat_file = '~/.vim/cheatsheet'
nnoremap <C-h> :Cheat<CR>

"setting on mac
"'mac' is not running so use 'unix'
if has('unix')
"let ostype = system("uname")
"if ostype == "Darwin"
	nnoremap あ a
	nnoremap い i
	nnoremap う u
	nnoremap お o
	nnoremap っd dd
	nnoremap っy yy	
endif

augroup vimrcEx
  au BufRead * if line("'\"") > 0 && line("'\"") <= line("$") |
  \ exe "normal g`\"" | endif
augroup END
